name: "Lines of code statistics"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
jobs:
  loc:
    name: Lines of code
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          go install github.com/hhatto/gocloc/cmd/gocloc@latest
      - name: All sources
        run: |
          cd $GITHUB_WORKSPACE
          gocloc .
      - name: All sources
        run: |
          cd $GITHUB_WORKSPACE
          gocloc .